@baseUrl = http://localhost:3001

### Auth
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "senha123"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@email.com",
  "password": "senha123"
}
 
