@baseUrl = http://localhost:3001
@jwtToken = {{authLogin.response.body.accessToken}}

### Auth
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "senha123"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@email.com",
  "password": "senha123"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjY3YTAzZi0xZjczLTRhYjctOTlkMC02YmMyMzZmNGNjNzkiLCJlbWFpbCI6InVzZXIxQGVtYWlsLmNvbSIsImlhdCI6MTc2OTI3Mjc3MywiZXhwIjoxNzY5MzU5MTczfQ.jZuR2-p8suYeQsmkFB6C3OfpVPC49YMLQI6S5LRaxLk
 
