@baseUrl = http://localhost:3001
@jwtToken = {{authLogin.response.body.accessToken}}

### Auth
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user2@email.com",
  "password": "123456"
}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "user2",
  "email": "user2@email.com",
  "password": "senha123"
}

### Read users
# @name readUsers
GET {{baseUrl}}/user
Authorization: Bearer {{jwtToken}}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "name": "123123123",
  "email": "user10@email.com"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "currentPassword": "senha123",
  "newPassword": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}